import {  Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar/Navbar";
import NextAuthProvider from "@/Providers/NextAuthProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased `}
      >
        <NextAuthProvider>
          {children}
      <Toaster position="top-right" reverseOrder={false} />
        </NextAuthProvider>
        
      </body>
    </html>
  );
}
